media:
  input: public
  output: /

content:
  - name: links
    label: Links
    path: app/content/links.toml
    type: file
    format: toml
    fields:
      - name: sections
        label: Sections
        type: object
        list: true
        fields: 
          - { name: heading, label: Heading, type: string, required: true }
          - name: links
            label: Links
            type: object
            list: true
            required: true
            fields:
              - { name: title, label: Title, type: string, required: true }
              - { name: url, label: URL, type: string, required: true }
              - { name: icon, label: Icon, type: string }
      
